name: Python CI

on:
  pull_request:
    branches: [master]

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./exercise_2
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
        run: |
          python -m pip install --upgrade pip
          pip install flake8 black
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: lint
        run: |
          black --check .
          flake8 .
  unittest:
    runs-on: ubuntu-latest
    steps:
      - name: pytest
        run: pytest .
