name: Protected envs and stages

on:
  

jobs:
  hello-greet-js:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - id: foo
        uses: ./.github/actions/greet
        with:
          who-to-greet: 'Mona the Octocat'
