name: Protected envs and stages

on:
  schedule:
    - cron: "*/5 * * * *"

jobs:
  hello-greet-js:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - id: foo
        uses: ./.github/actions/custom.yaml
        with:
          who-to-greet: 'Mona the Octocat'

      - run: echo random-number "$RANDOM_NUMBER"
        shell: bash
        env:
          RANDOM_NUMBER: ${{ steps.foo.outputs.random-number }}
